// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/gabrielmvnog/go-coupon/customer/src/models"
	mock "github.com/stretchr/testify/mock"
)

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: ctx, customer
func (_m *CustomerRepository) CreateCustomer(ctx context.Context, customer *models.Customer) (*models.Customer, error) {
	ret := _m.Called(ctx, customer)

	var r0 *models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Customer) (*models.Customer, error)); ok {
		return rf(ctx, customer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Customer) *models.Customer); ok {
		r0 = rf(ctx, customer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Customer) error); ok {
		r1 = rf(ctx, customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCustomer provides a mock function with given fields: ctx, customer_id
func (_m *CustomerRepository) DeleteCustomer(ctx context.Context, customer_id uint32) error {
	ret := _m.Called(ctx, customer_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) error); ok {
		r0 = rf(ctx, customer_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCustomerById provides a mock function with given fields: ctx, customer_id
func (_m *CustomerRepository) GetCustomerById(ctx context.Context, customer_id uint32) (*models.Customer, error) {
	ret := _m.Called(ctx, customer_id)

	var r0 *models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32) (*models.Customer, error)); ok {
		return rf(ctx, customer_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32) *models.Customer); ok {
		r0 = rf(ctx, customer_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = rf(ctx, customer_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCustomer provides a mock function with given fields: ctx, customer_id, customer
func (_m *CustomerRepository) UpdateCustomer(ctx context.Context, customer_id uint32, customer *models.Customer) (*models.Customer, error) {
	ret := _m.Called(ctx, customer_id, customer)

	var r0 *models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint32, *models.Customer) (*models.Customer, error)); ok {
		return rf(ctx, customer_id, customer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint32, *models.Customer) *models.Customer); ok {
		r0 = rf(ctx, customer_id, customer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint32, *models.Customer) error); ok {
		r1 = rf(ctx, customer_id, customer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCustomerRepository creates a new instance of CustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerRepository {
	mock := &CustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
