version: '3.1'

services:
  backend_for_frontend:
    build: bff/
    ports:
      - 3000:3000

  customer_service:
    build: customer/
    ports:
      - 9000:9000
    environment:
      - DB_USER=shared
      - DB_PASSWORD=shared
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=shared

  coupon_service:
    build: coupon/
    ports:
      - 9001:9000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: shared
      POSTGRES_USER: shared
      POSTGRES_DB: shared
    ports:
      - 5432:5432
