version: '3.1'

services:

  customer_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: customer
      POSTGRES_USER: customer
      POSTGRES_DB: customer
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
